#!/usr/bin/env python3
"""Convert UCD break test files into MoonBit data tables.

Each test row in the source is `÷ CCCC × DDDD ÷` etc.: codepoints
separated by `÷` (boundary) or `×` (no boundary). We emit the
codepoint string and the expected UTF-16 boundary array.

Reads:
  testdata/GraphemeBreakTest.txt
  testdata/WordBreakTest.txt

Writes:
  graphemebreaktest_cases_wbtest.mbt   (one Array[(String, Array[Int])])
  wordbreaktest_cases_wbtest.mbt       (one Array[(String, Array[Int])])
"""

import os
import sys

DIVIDE = "÷"  # ÷
NO_DIVIDE = "×"  # ×


def utf16_len(cp: int) -> int:
    return 2 if cp >= 0x10000 else 1


def escape_codepoint(cp: int) -> str:
    """MoonBit string escape for a codepoint."""
    return f"\\u{{{cp:X}}}"


def parse_test_line(line: str):
    """Return (codepoints, boundaries_after_each_codepoint).

    boundaries_after_each_codepoint[i] = True if there's a boundary
    AFTER the i-th codepoint. Plus boundary at start (always True).
    """
    line = line.split("#", 1)[0].strip()
    if not line:
        return None
    tokens = line.split()
    # Tokens alternate: ÷/× CP ÷/× CP ÷/× ... ÷
    # First token must be ÷ (boundary at start), last must be ÷ (boundary at end).
    if not tokens or tokens[0] != DIVIDE:
        return None
    cps = []
    boundaries_after = []
    i = 1
    while i < len(tokens):
        try:
            cp = int(tokens[i], 16)
        except ValueError:
            return None
        cps.append(cp)
        i += 1
        if i >= len(tokens):
            return None
        sep = tokens[i]
        boundaries_after.append(sep == DIVIDE)
        i += 1
    return cps, boundaries_after


def read_cases(src):
    cases = []
    with open(src, encoding="utf-8") as f:
        for line in f:
            parsed = parse_test_line(line)
            if not parsed:
                continue
            cps, boundaries_after = parsed
            # Build UTF-16 boundary array.
            text_lit_parts = []
            cumulative = 0
            boundaries = [0]
            for cp, has_boundary_after in zip(cps, boundaries_after):
                text_lit_parts.append(escape_codepoint(cp))
                cumulative += utf16_len(cp)
                if has_boundary_after:
                    boundaries.append(cumulative)
            # Last entry of boundaries should equal cumulative (text length).
            # If the test row's final boundary was already appended, this is a no-op.
            if boundaries[-1] != cumulative:
                # Last sep in source was × — break_test_internal contract violated.
                # Spec rule GB2 (boundary at eot) is implied; force it.
                boundaries.append(cumulative)
            text_lit = "".join(text_lit_parts)
            cases.append((text_lit, boundaries))
    return cases


def write_cases(dst, cases, source_name, value_name, break_name):
    out = []
    out.append("// AUTO-GENERATED by lib/moji/scripts/gen_break_test_cases.py")
    out.append(f"// DO NOT EDIT BY HAND. Source: Unicode 15.1 {source_name}")
    out.append(f"// {len(cases)} test rows.")
    out.append("")
    out.append("///|")
    out.append(
        "/// `(text, expected_utf16_boundaries)` rows lifted verbatim from"
    )
    out.append(f"/// `{source_name}` (Unicode 15.1). Used by the opt-in")
    out.append("/// conformance test to verify the segmentation algorithm against")
    out.append("/// the full UAX #29 reference suite.")
    out.append(f"let {value_name} : Array[(String, Array[Int])] = [")
    for text, bs in cases:
        bs_str = "[" + ", ".join(str(b) for b in bs) + "]"
        out.append(f'  ("{text}", {bs_str}),')
    out.append("]")
    out.append("")

    with open(dst, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print(f"wrote {dst}: {len(cases)} {break_name} cases", file=sys.stderr)


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    moji = os.path.dirname(here)

    specs = [
        (
            "GraphemeBreakTest.txt",
            "graphemebreaktest_cases_wbtest.mbt",
            "break_test_cases",
            "grapheme",
        ),
        (
            "WordBreakTest.txt",
            "wordbreaktest_cases_wbtest.mbt",
            "word_break_test_cases",
            "word",
        ),
    ]
    for source_name, dst_name, value_name, break_name in specs:
        src = os.path.join(moji, "testdata", source_name)
        dst = os.path.join(moji, dst_name)
        write_cases(dst, read_cases(src), source_name, value_name, break_name)


if __name__ == "__main__":
    main()
