#!/usr/bin/env node
// Run a non-gating CommonMark 0.31.2 HTML conformance audit.
//
// The script fetches or reads the official CommonMark spec.json, writes a
// temporary MoonBit test that exercises the MarkdownIR -> CommonMark HTML
// adapter over every example, runs only that generated audit test, then removes
// the generated file. Normal `moon test` stays hermetic and curated.

import { readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawnSync } from 'node:child_process'

const COMMONMARK_VERSION = '0.31.2'
const DEFAULT_SPEC_URL = `https://spec.commonmark.org/${COMMONMARK_VERSION}/spec.json`

const __dirname = dirname(fileURLToPath(import.meta.url))
const markdownRoot = join(__dirname, '..')
const generatedPath = join(markdownRoot, 'src', 'commonmark_html_audit_generated_test.mbt')
const generatedRel = relative(markdownRoot, generatedPath)

function usage() {
  console.log(`Usage: node tools/commonmark_html_audit.mjs [--spec path-or-url] [--keep-generated]\n\n` +
    `Fetches ${DEFAULT_SPEC_URL} by default and runs a temporary MoonBit audit test.\n` +
    `Use --spec with a local spec.json path for offline runs.`)
}

function parseArgs(argv) {
  let spec = DEFAULT_SPEC_URL
  let keepGenerated = false
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i]
    switch (arg) {
      case '--help':
      case '-h':
        usage()
        process.exit(0)
      case '--keep-generated':
        keepGenerated = true
        break
      case '--spec':
        if (i + 1 >= argv.length) throw new Error('--spec requires a path or URL')
        spec = argv[i + 1]
        i += 1
        break
      default:
        throw new Error(`unknown argument: ${arg}`)
    }
  }
  return { spec, keepGenerated }
}

async function loadSpec(spec) {
  if (/^https?:\/\//.test(spec)) {
    const response = await fetch(spec)
    if (!response.ok) throw new Error(`failed to fetch ${spec}: HTTP ${response.status}`)
    return await response.json()
  }
  return JSON.parse(await readFile(spec, 'utf8'))
}

function moonString(text) {
  return JSON.stringify(text)
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029')
}

function moonIdent(text) {
  const ident = text.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '')
  return ident || 'section'
}

function commonmarkExampleNumber(example) {
  return example.example ?? example.number
}

function validateSpec(data) {
  if (!Array.isArray(data)) throw new Error('spec.json root must be an array')
  for (const [index, example] of data.entries()) {
    for (const field of ['section', 'markdown', 'html']) {
      if (typeof example[field] !== 'string') {
        throw new Error(`example at index ${index} is missing string field ${field}`)
      }
    }
    if (typeof commonmarkExampleNumber(example) !== 'number') {
      throw new Error(`example at index ${index} is missing numeric example/number`)
    }
  }
}

function groupBySection(examples) {
  const sections = []
  const byName = new Map()
  for (const example of examples) {
    const name = example.section
    if (!byName.has(name)) {
      const section = { name, examples: [] }
      byName.set(name, section)
      sections.push(section)
    }
    byName.get(name).examples.push(example)
  }
  return sections
}

function renderGeneratedAudit(specExamples) {
  const sections = groupBySection(specExamples)
  const lines = [
    '// Generated by examples/markdown/tools/commonmark_html_audit.mjs.',
    '// Temporary non-gating audit file; do not commit.',
    '',
    '///|',
    'struct CommonMarkAuditFixture {',
    '  example : Int',
    '  source : String',
    '  expected_html : String',
    '}',
    '',
    '///|',
    'struct CommonMarkAuditSection {',
    '  name : String',
    '  fixtures : Array[CommonMarkAuditFixture]',
    '}',
    '',
    '///|',
    'enum CommonMarkAuditOutcome {',
    '  AuditPass',
    '  AuditLexError',
    '  AuditUnsupportedIr',
    '  AuditParserDiagnostics',
    '  AuditMismatch',
    '} derive(Eq)',
    '',
    '///|',
    'fn CommonMarkAuditOutcome::label(self : CommonMarkAuditOutcome) -> String {',
    '  match self {',
    '    AuditPass => "pass"',
    '    AuditLexError => "lex-error"',
    '    AuditUnsupportedIr => "unsupported-ir"',
    '    AuditParserDiagnostics => "parser-diagnostics"',
    '    AuditMismatch => "mismatch"',
    '  }',
    '}',
    '',
    '///|',
    'fn CommonMarkAuditFixture::outcome(self : CommonMarkAuditFixture) -> CommonMarkAuditOutcome {',
    '  let (cst, diagnostics) = parse_cst(self.source) catch {',
    '    _ => return AuditLexError',
    '  }',
    '  let ir = experimental_markdown_ir_from_syntax_with_diagnostics(',
    '    @seam.SyntaxNode::from_cst(cst),',
    '    diagnostics,',
    '  )',
    '  let actual = experimental_markdown_ir_to_commonmark_html(ir)',
    '  if actual == self.expected_html {',
    '    AuditPass',
    '  } else if actual.contains("unsupported MarkdownIR") ||',
    '    actual.contains("recovered MarkdownIR") {',
    '    AuditUnsupportedIr',
    '  } else if diagnostics.length() > 0 {',
    '    AuditParserDiagnostics',
    '  } else {',
    '    AuditMismatch',
    '  }',
    '}',
    '',
    '///|',
    'fn audit_count(',
    '  outcome : CommonMarkAuditOutcome,',
    '  pass : Int,',
    '  lex_error : Int,',
    '  unsupported_ir : Int,',
    '  parser_diagnostics : Int,',
    '  mismatch : Int,',
    ') -> (Int, Int, Int, Int, Int) {',
    '  match outcome {',
    '    AuditPass => (pass + 1, lex_error, unsupported_ir, parser_diagnostics, mismatch)',
    '    AuditLexError => (pass, lex_error + 1, unsupported_ir, parser_diagnostics, mismatch)',
    '    AuditUnsupportedIr => (pass, lex_error, unsupported_ir + 1, parser_diagnostics, mismatch)',
    '    AuditParserDiagnostics => (pass, lex_error, unsupported_ir, parser_diagnostics + 1, mismatch)',
    '    AuditMismatch => (pass, lex_error, unsupported_ir, parser_diagnostics, mismatch + 1)',
    '  }',
    '}',
    '',
    '///|',
    'fn audit_section(section : CommonMarkAuditSection) -> (Int, Int, Int, Int, Int) {',
    '  for fixture in section.fixtures; pass = 0, lex_error = 0, unsupported_ir = 0, parser_diagnostics = 0, mismatch = 0 {',
    '    let outcome = fixture.outcome()',
    '    println(',
    '      "example\t" +',
    '      section.name +',
    '      "\t" +',
    '      fixture.example.to_string() +',
    '      "\t" +',
    '      outcome.label(),',
    '    )',
    '    let (next_pass, next_lex_error, next_unsupported_ir, next_parser_diagnostics, next_mismatch) =',
    '      audit_count(',
    '        outcome,',
    '        pass,',
    '        lex_error,',
    '        unsupported_ir,',
    '        parser_diagnostics,',
    '        mismatch,',
    '      )',
    '    continue next_pass, next_lex_error, next_unsupported_ir, next_parser_diagnostics, next_mismatch',
    '  } nobreak {',
    '    println(',
    '      "section\t" +',
    '      section.name +',
    '      "\tpass=" +',
    '      pass.to_string() +',
    '      "\tfail=" +',
    '      (lex_error + unsupported_ir + parser_diagnostics + mismatch).to_string() +',
    '      "\tskip=0\tlex-error=" +',
    '      lex_error.to_string() +',
    '      "\tunsupported-ir=" +',
    '      unsupported_ir.to_string() +',
    '      "\tparser-diagnostics=" +',
    '      parser_diagnostics.to_string() +',
    '      "\tmismatch=" +',
    '      mismatch.to_string(),',
    '    )',
    '    (pass, lex_error, unsupported_ir, parser_diagnostics, mismatch)',
    '  }',
    '}',
    '',
  ]

  for (const section of sections) {
    const ident = moonIdent(section.name)
    lines.push('///|')
    lines.push(`fn commonmark_audit_${ident}_fixtures() -> Array[CommonMarkAuditFixture] {`)
    lines.push('  [')
    for (const example of section.examples) {
      lines.push('    {')
      lines.push(`      example: ${commonmarkExampleNumber(example)},`)
      lines.push(`      source: ${moonString(example.markdown)},`)
      lines.push(`      expected_html: ${moonString(example.html)},`)
      lines.push('    },')
    }
    lines.push('  ]')
    lines.push('}')
    lines.push('')
  }

  lines.push('///|')
  lines.push('fn commonmark_audit_sections() -> Array[CommonMarkAuditSection] {')
  lines.push('  [')
  for (const section of sections) {
    const ident = moonIdent(section.name)
    lines.push('    {')
    lines.push(`      name: ${moonString(section.name)},`)
    lines.push(`      fixtures: commonmark_audit_${ident}_fixtures(),`)
    lines.push('    },')
  }
  lines.push('  ]')
  lines.push('}')
  lines.push('')
  lines.push('///|')
  lines.push('test "CommonMark full-corpus HTML audit" {')
  lines.push(`  println("CommonMark ${COMMONMARK_VERSION} full-corpus HTML audit")`)
  lines.push('  println("kind\tsection\texample\tcategory")')
  lines.push('  let (pass, lex_error, unsupported_ir, parser_diagnostics, mismatch) =')
  lines.push('    for section in commonmark_audit_sections(); total_pass = 0, total_lex_error = 0, total_unsupported_ir = 0, total_parser_diagnostics = 0, total_mismatch = 0 {')
  lines.push('      let (section_pass, section_lex_error, section_unsupported_ir, section_parser_diagnostics, section_mismatch) =')
  lines.push('        audit_section(section)')
  lines.push('      continue total_pass + section_pass, total_lex_error + section_lex_error, total_unsupported_ir + section_unsupported_ir, total_parser_diagnostics + section_parser_diagnostics, total_mismatch + section_mismatch')
  lines.push('    } nobreak {')
  lines.push('      (total_pass, total_lex_error, total_unsupported_ir, total_parser_diagnostics, total_mismatch)')
  lines.push('    }')
  lines.push('  let fail = lex_error + unsupported_ir + parser_diagnostics + mismatch')
  lines.push('  println(')
  lines.push('    "total\tall\tpass=" +')
  lines.push('    pass.to_string() +')
  lines.push('    "\tfail=" +')
  lines.push('    fail.to_string() +')
  lines.push('    "\tskip=0\tlex-error=" +')
  lines.push('    lex_error.to_string() +')
  lines.push('    "\tunsupported-ir=" +')
  lines.push('    unsupported_ir.to_string() +')
  lines.push('    "\tparser-diagnostics=" +')
  lines.push('    parser_diagnostics.to_string() +')
  lines.push('    "\tmismatch=" +')
  lines.push('    mismatch.to_string(),')
  lines.push('  )')
  lines.push('}')
  lines.push('')
  return lines.join('\n')
}

async function main() {
  const { spec, keepGenerated } = parseArgs(process.argv.slice(2))
  const specExamples = await loadSpec(spec)
  validateSpec(specExamples)
  await writeFile(generatedPath, renderGeneratedAudit(specExamples), 'utf8')
  console.error(`Wrote temporary audit test: ${generatedRel}`)
  try {
    const result = spawnSync(
      'moon',
      ['test', generatedRel, '--filter', 'CommonMark full-corpus HTML audit'],
      {
        cwd: markdownRoot,
        stdio: 'inherit',
        env: { ...process.env, NEW_MOON_MOD: '0' },
      },
    )
    if (result.error) throw result.error
    process.exitCode = result.status ?? 1
  } finally {
    if (!keepGenerated) await rm(generatedPath, { force: true })
  }
}

main().catch(error => {
  console.error(error instanceof Error ? error.message : String(error))
  process.exit(1)
})
