#!/usr/bin/env node
// Regenerate the embedded MarkdownIR -> mdast fixture parity data.
//
// This tool is optional and intentionally not part of MoonBit CI. Run it with a
// Node environment that can resolve mdast-util-from-markdown, for example:
//   npm exec --package=mdast-util-from-markdown -- node tools/update_mdast_fixtures.mjs

import { existsSync } from 'node:fs'
import { writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const fixtures = [
  { name: 'heading', source: '# Title\n', status: 'pass' },
  { name: 'paragraph-plain-text', source: 'Hello world\n', status: 'pass' },
  { name: 'unordered-list', source: '- one\n- two\n', status: 'pass' },
  { name: 'nested-unordered-list', source: '- a\n  - b\n', status: 'pass' },
  {
    name: 'nested-unordered-list-multiple-items',
    source: '- a\n  - b\n  - c\n',
    status: 'pass',
  },
  {
    name: 'nested-unordered-list-top-level-resumption',
    source: '- a\n  - b\n- c\n',
    status: 'pass',
  },
  {
    name: 'indented-unordered-list-markers',
    source: '- a\n - b\n  - c\n   - d\n  - e\n - f\n- g\n',
    status: 'pass',
  },
  {
    name: 'indented-ordered-list-markers-loose',
    source: '1. a\n\n  2. b\n\n   3. c\n',
    status: 'pass',
  },
  { name: 'fenced-code', source: '```moonbit\nlet x = 1\n```\n', status: 'pass' },
  { name: 'strong', source: '**world**\n', status: 'pass' },
  { name: 'emphasis', source: '*moon*\n', status: 'pass' },
  { name: 'inline-code', source: '`code`\n', status: 'pass' },
  { name: 'link', source: '[link](https://example.com/a)\n', status: 'pass' },
]

const __dirname = dirname(fileURLToPath(import.meta.url))
const output = join(__dirname, '..', 'src', 'mdast_fixture_data_test.mbt')

async function loadFromMarkdown() {
  try {
    return await import('mdast-util-from-markdown')
  } catch (initialError) {
    for (const entry of process.env.PATH?.split(':') ?? []) {
      if (!entry.endsWith('/node_modules/.bin')) continue
      const candidate = join(dirname(entry), 'mdast-util-from-markdown', 'index.js')
      if (existsSync(candidate)) return await import(pathToFileURL(candidate).href)
    }

    console.error('Unable to import mdast-util-from-markdown.')
    console.error('Run with: npm exec --package=mdast-util-from-markdown -- node tools/update_mdast_fixtures.mjs')
    console.error(initialError instanceof Error ? initialError.message : String(initialError))
    process.exit(1)
  }
}

const { fromMarkdown } = await loadFromMarkdown()

function canonicalizeMdast(value) {
  if (Array.isArray(value)) return value.map(canonicalizeMdast)
  if (!value || typeof value !== 'object') return value

  const canonical = {}
  const preferredOrder = ['type', 'depth', 'ordered', 'lang', 'value', 'url', 'children']
  const source = {}

  for (const [key, child] of Object.entries(value)) {
    if (key === 'position') continue
    if (child === null) continue
    if (key === 'spread' && child === false) continue
    if (key === 'start' && child === 1) continue
    source[key] = canonicalizeMdast(child)
  }

  for (const key of preferredOrder) {
    if (Object.hasOwn(source, key)) canonical[key] = source[key]
  }
  for (const key of Object.keys(source).sort()) {
    if (!Object.hasOwn(canonical, key)) canonical[key] = source[key]
  }
  return canonical
}

function moonString(text) {
  return JSON.stringify(text)
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029')
}

function statusExpr(fixture) {
  switch (fixture.status) {
    case 'pass':
      return 'Pass'
    case 'xfail':
      return `Xfail(${moonString(fixture.reason ?? 'expected fixture mismatch')})`
    case 'skip':
      return `Skip(${moonString(fixture.reason ?? 'skipped fixture')})`
    default:
      throw new Error(`unknown fixture status for ${fixture.name}: ${fixture.status}`)
  }
}

const counts = { pass: 0, xfail: 0, skip: 0 }
for (const fixture of fixtures) counts[fixture.status] += 1

const lines = [
  '// Generated by examples/markdown/tools/update_mdast_fixtures.mjs.',
  '// Do not edit expected JSON by hand; edit fixture metadata in the generator,',
  '// then regenerate. The embedded data keeps `moon test` hermetic: no Node/npm or',
  '// network access is needed during normal MoonBit CI.',
  `// Baseline: pass=${counts.pass}, xfail=${counts.xfail}, skip=${counts.skip}.`,
  '',
  '///|',
  'fn mdast_fixture_expected_status_counts() -> (Int, Int, Int) {',
  `  (${counts.pass}, ${counts.xfail}, ${counts.skip})`,
  '}',
  '',
  '///|',
  'fn mdast_fixture_cases() -> Array[MdastFixture] {',
  '  [',
]

for (const fixture of fixtures) {
  const expected = JSON.stringify(canonicalizeMdast(fromMarkdown(fixture.source)))
  lines.push('    {')
  lines.push(`      name: ${moonString(fixture.name)},`)
  lines.push(`      source: ${moonString(fixture.source)},`)
  lines.push(`      expected: ${moonString(expected)},`)
  lines.push(`      status: ${statusExpr(fixture)},`)
  lines.push('    },')
}

lines.push('  ]')
lines.push('}')
lines.push('')

await writeFile(output, lines.join('\n'), 'utf8')
console.log(`Wrote ${output}`)
