#!/usr/bin/env python3
"""Regenerate JSONTestSuite spec-compliance tests for examples/json.

The generated MoonBit tests embed pinned upstream fixtures so CI stays
hermetic: `moon test` does not fetch from the network. The generated assertions
cover JSONTestSuite's required `y_` and `n_` cases that can be represented by
the current String API; they intentionally do not claim formal proof or raw byte
encoding validation.
"""

from __future__ import annotations

import io
import os
import tarfile
import urllib.request
from dataclasses import dataclass
from pathlib import Path

JSONTESTSUITE_REPO = "nst/JSONTestSuite"
JSONTESTSUITE_REV = "1ef36fa01286573e846ac449e8683f8833c5b26a"
JSONTESTSUITE_TARBALL = (
    f"https://api.github.com/repos/{JSONTESTSUITE_REPO}/tarball/{JSONTESTSUITE_REV}"
)
CHUNK_CODEPOINTS = 1000

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src" / "json_testsuite_generated_wbtest.mbt"


@dataclass(frozen=True)
class Case:
    name: str
    source: str


def fetch_tarball() -> bytes:
    request = urllib.request.Request(
        JSONTESTSUITE_TARBALL,
        headers={"User-Agent": "loom-json-conformance-generator"},
    )
    with urllib.request.urlopen(request, timeout=90) as response:
        return response.read()


def moon_string_literal(text: str) -> str:
    parts: list[str] = []
    for char in text:
        codepoint = ord(char)
        if char == "\\":
            parts.append("\\\\")
        elif char == '"':
            parts.append('\\"')
        elif char == "\n":
            parts.append("\\n")
        elif char == "\r":
            parts.append("\\r")
        elif char == "\t":
            parts.append("\\t")
        elif char == "\b":
            parts.append("\\b")
        elif char == "\f":
            parts.append("\\f")
        elif codepoint < 0x20:
            parts.append(f"\\u{codepoint:04X}")
        elif codepoint < 0x7F:
            parts.append(char)
        elif codepoint <= 0xFFFF:
            parts.append(f"\\u{codepoint:04X}")
        else:
            parts.append(f"\\u{{{codepoint:X}}}")
    return '"' + "".join(parts) + '"'


def moon_string_expr(text: str, indent: str) -> str:
    if len(text) <= CHUNK_CODEPOINTS:
        return moon_string_literal(text)
    chunks = [text[i : i + CHUNK_CODEPOINTS] for i in range(0, len(text), CHUNK_CODEPOINTS)]
    return (" +\n" + indent).join(moon_string_literal(chunk) for chunk in chunks)


def load_cases(tarball: bytes) -> tuple[list[Case], list[Case], list[str], list[str]]:
    valid: list[Case] = []
    invalid: list[Case] = []
    implementation_defined: list[str] = []
    skipped_non_utf8: list[str] = []
    with tarfile.open(fileobj=io.BytesIO(tarball), mode="r:gz") as archive:
        members = sorted(archive.getmembers(), key=lambda member: member.name)
        for member in members:
            name = os.path.basename(member.name)
            if "/test_parsing/" not in member.name or not member.isfile():
                continue
            if not name.endswith(".json"):
                continue
            raw = archive.extractfile(member).read()  # type: ignore[union-attr]
            try:
                source = raw.decode("utf-8", "strict")
            except UnicodeDecodeError:
                skipped_non_utf8.append(name)
                continue
            if name.startswith("y_"):
                valid.append(Case(name, source))
            elif name.startswith("n_"):
                invalid.append(Case(name, source))
            elif name.startswith("i_"):
                implementation_defined.append(name)
    return valid, invalid, implementation_defined, skipped_non_utf8


def append_case_array(lines: list[str], cases: list[Case]) -> None:
    lines.append("  let cases : Array[(String, String)] = [")
    for case in cases:
        lines.append("    (")
        lines.append(f"      {moon_string_literal(case.name)},")
        lines.append(f"      {moon_string_expr(case.source, indent='      ')},")
        lines.append("    ),")
    lines.append("  ]")


def render_generated(
    valid: list[Case],
    invalid: list[Case],
    implementation_defined: list[str],
    skipped_non_utf8: list[str],
) -> str:
    lines: list[str] = []
    lines.extend(
        [
            "// Generated by examples/json/tools/update_json_conformance_tests.py.",
            "// Do not edit by hand.",
            f"// Source: https://github.com/{JSONTESTSUITE_REPO}/tree/{JSONTESTSUITE_REV}/test_parsing",
            "// Upstream license: MIT.",
            "//",
            "// Spec-compliance assertion policy:",
            "// - y_*.json fixtures must be accepted by strict parse(...).",
            "// - n_*.json fixtures must be rejected by strict parse(...).",
            "// - i_*.json fixtures are implementation-defined and are not asserted.",
            "// - non-UTF-8 fixtures are skipped because parse(...) accepts MoonBit String, not raw Bytes.",
            "// This is a practical JSONTestSuite compliance gate, not a formal proof of RFC 8259.",
            f"// Generated counts: y={len(valid)}, n={len(invalid)}, i_skipped={len(implementation_defined)}, non_utf8_skipped={len(skipped_non_utf8)}.",
            "//",
            "// Implementation-defined fixtures not asserted:",
        ]
    )
    for name in implementation_defined:
        lines.append(f"// - {name}")
    lines.append("//")
    lines.append("// Non-UTF-8 fixtures outside the current String API boundary:")
    for name in skipped_non_utf8:
        lines.append(f"// - {name}")
    lines.extend(
        [
            "",
            "///|",
            "fn json_testsuite_accepts(source : String) -> Bool {",
            "  try parse(source) catch {",
            "    _ => false",
            "  } noraise {",
            "    _ => true",
            "  }",
            "}",
            "",
            "///|",
            'test "JSONTestSuite: required valid cases" {',
        ]
    )
    append_case_array(lines, valid)
    lines.extend(
        [
            "  for case in cases {",
            "    let (name, source) = case",
            "    guard json_testsuite_accepts(source) else {",
            '      fail("JSONTestSuite valid case rejected: " + name)',
            "    }",
            "  }",
            "}",
            "",
            "///|",
            'test "JSONTestSuite: required invalid cases" {',
        ]
    )
    append_case_array(lines, invalid)
    lines.extend(
        [
            "  for case in cases {",
            "    let (name, source) = case",
            "    guard !json_testsuite_accepts(source) else {",
            '      fail("JSONTestSuite invalid case accepted: " + name)',
            "    }",
            "  }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    tarball = fetch_tarball()
    valid, invalid, implementation_defined, skipped_non_utf8 = load_cases(tarball)
    OUTPUT.write_text(
        render_generated(valid, invalid, implementation_defined, skipped_non_utf8),
        encoding="utf-8",
    )
    print(f"wrote {OUTPUT}")
    print(
        f"JSONTestSuite {JSONTESTSUITE_REV}: "
        f"y={len(valid)} n={len(invalid)} "
        f"i_skipped={len(implementation_defined)} "
        f"non_utf8_skipped={len(skipped_non_utf8)}"
    )


if __name__ == "__main__":
    main()
