#!/usr/bin/env python3
"""Generate MoonBit property tables from Unicode 15.1 UCD data.

Reads:
  testdata/GraphemeBreakProperty.txt   (Grapheme_Cluster_Break)
  testdata/WordBreakProperty.txt       (Word_Break)
  testdata/emoji-data.txt               (Extended_Pictographic)
  testdata/DerivedCoreProperties.txt    (InCB)

Writes:
  property_tables.mbt                   (interval arrays + lookup helpers)

Invariant: arrays are sorted by `start`, with non-overlapping inclusive ranges.
Lookup is binary search.
"""

import re
import sys
import os
from collections import defaultdict

UCD_LINE = re.compile(
    r"^\s*([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*([A-Za-z_]+)(?:\s*;\s*([A-Za-z_]+))?"
)


def parse_property_file(path, accepted_props, prop_index=0):
    """Return dict: prop_name -> sorted list of (start, end) inclusive ranges (merged)."""
    raw = defaultdict(list)
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            m = UCD_LINE.match(line)
            if not m:
                continue
            start_h, end_h, prop1, prop2 = m.groups()
            prop = (prop1, prop2)[prop_index]
            if not prop or prop not in accepted_props:
                continue
            start = int(start_h, 16)
            end = int(end_h, 16) if end_h else start
            raw[prop].append((start, end))
    return {p: merge_ranges(rs) for p, rs in raw.items()}


def merge_ranges(rs):
    rs = sorted(rs)
    out = []
    for s, e in rs:
        if out and s <= out[-1][1] + 1:
            out[-1] = (out[-1][0], max(out[-1][1], e))
        else:
            out.append((s, e))
    return out


def emit_interval_array(name, ranges, doc):
    """Emit a MoonBit `let` of a flat Array[Int] with [start0, end0, start1, end1, ...]."""
    flat = []
    for s, e in ranges:
        flat.append(s)
        flat.append(e)
    if not flat:
        body = "[]"
    else:
        # 8 ints per line for readability
        chunks = []
        for i in range(0, len(flat), 8):
            chunks.append(", ".join(f"0x{v:X}" for v in flat[i : i + 8]))
        body = "[\n  " + ",\n  ".join(chunks) + ",\n]"
    return (
        f"///| {doc}\n"
        f"/// Flat `[start0, end0, start1, end1, ...]` interval array (inclusive). "
        f"{len(ranges)} ranges.\n"
        f"let {name} : Array[Int] = {body}\n"
    )


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    moji = os.path.dirname(here)
    testdata = os.path.join(moji, "testdata")

    gcb_path = os.path.join(testdata, "GraphemeBreakProperty.txt")
    wb_path = os.path.join(testdata, "WordBreakProperty.txt")
    emoji_path = os.path.join(testdata, "emoji-data.txt")
    dcp_path = os.path.join(testdata, "DerivedCoreProperties.txt")

    gcb_props = {
        "CR",
        "LF",
        "Control",
        "Extend",
        "ZWJ",
        "Regional_Indicator",
        "Prepend",
        "SpacingMark",
        "L",
        "V",
        "T",
        "LV",
        "LVT",
    }
    gcb = parse_property_file(gcb_path, gcb_props, prop_index=0)
    wb_props = {
        "CR",
        "LF",
        "Newline",
        "Extend",
        "ZWJ",
        "Format",
        "Regional_Indicator",
        "Katakana",
        "Hebrew_Letter",
        "ALetter",
        "Single_Quote",
        "Double_Quote",
        "MidNumLet",
        "MidLetter",
        "MidNum",
        "Numeric",
        "ExtendNumLet",
        "WSegSpace",
    }
    wb = parse_property_file(wb_path, wb_props, prop_index=0)
    emoji = parse_property_file(emoji_path, {"Extended_Pictographic"}, prop_index=0)
    incb_props = {"InCB"}
    # DerivedCoreProperties.txt format: "0915 ; InCB; Consonant" — prop_index=0 is "InCB"; we want prop_index=1 for the value.
    # Re-parse manually to capture the value column.

    incb = {"Consonant": [], "Extend": [], "Linker": []}
    with open(dcp_path, encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            m = UCD_LINE.match(line)
            if not m:
                continue
            start_h, end_h, prop1, prop2 = m.groups()
            if prop1 != "InCB" or prop2 not in incb:
                continue
            start = int(start_h, 16)
            end = int(end_h, 16) if end_h else start
            incb[prop2].append((start, end))
    incb = {k: merge_ranges(v) for k, v in incb.items()}

    out_lines = [
        "// AUTO-GENERATED by lib/moji/scripts/gen_property_tables.py",
        "// DO NOT EDIT BY HAND. Source: Unicode 15.1 UCD",
        "//   GraphemeBreakProperty.txt, WordBreakProperty.txt,",
        "//   emoji-data.txt, DerivedCoreProperties.txt",
        "//",
        "// Each table is a flat Array[Int] of [start0, end0, start1, end1, ...]",
        "// inclusive code-point ranges, sorted by start, non-overlapping.",
        "// Lookup via binary_search_range/2 in property.mbt.",
        "",
    ]

    table_specs = [
        ("table_cr", gcb.get("CR", []), "Grapheme_Cluster_Break = CR"),
        ("table_lf", gcb.get("LF", []), "Grapheme_Cluster_Break = LF"),
        ("table_control", gcb.get("Control", []), "Grapheme_Cluster_Break = Control"),
        ("table_extend", gcb.get("Extend", []), "Grapheme_Cluster_Break = Extend"),
        ("table_zwj", gcb.get("ZWJ", []), "Grapheme_Cluster_Break = ZWJ"),
        (
            "table_regional_indicator",
            gcb.get("Regional_Indicator", []),
            "Grapheme_Cluster_Break = Regional_Indicator",
        ),
        ("table_prepend", gcb.get("Prepend", []), "Grapheme_Cluster_Break = Prepend"),
        (
            "table_spacing_mark",
            gcb.get("SpacingMark", []),
            "Grapheme_Cluster_Break = SpacingMark",
        ),
        ("table_l", gcb.get("L", []), "Grapheme_Cluster_Break = L"),
        ("table_v", gcb.get("V", []), "Grapheme_Cluster_Break = V"),
        ("table_t", gcb.get("T", []), "Grapheme_Cluster_Break = T"),
        ("table_lv", gcb.get("LV", []), "Grapheme_Cluster_Break = LV"),
        ("table_lvt", gcb.get("LVT", []), "Grapheme_Cluster_Break = LVT"),
        (
            "table_extended_pictographic",
            emoji.get("Extended_Pictographic", []),
            "Extended_Pictographic = True",
        ),
        ("table_incb_consonant", incb.get("Consonant", []), "InCB = Consonant"),
        ("table_incb_extend", incb.get("Extend", []), "InCB = Extend"),
        ("table_incb_linker", incb.get("Linker", []), "InCB = Linker"),
        ("table_wb_cr", wb.get("CR", []), "Word_Break = CR"),
        ("table_wb_lf", wb.get("LF", []), "Word_Break = LF"),
        ("table_wb_newline", wb.get("Newline", []), "Word_Break = Newline"),
        ("table_wb_extend", wb.get("Extend", []), "Word_Break = Extend"),
        ("table_wb_zwj", wb.get("ZWJ", []), "Word_Break = ZWJ"),
        ("table_wb_format", wb.get("Format", []), "Word_Break = Format"),
        (
            "table_wb_regional_indicator",
            wb.get("Regional_Indicator", []),
            "Word_Break = Regional_Indicator",
        ),
        ("table_wb_katakana", wb.get("Katakana", []), "Word_Break = Katakana"),
        (
            "table_wb_hebrew_letter",
            wb.get("Hebrew_Letter", []),
            "Word_Break = Hebrew_Letter",
        ),
        ("table_wb_aletter", wb.get("ALetter", []), "Word_Break = ALetter"),
        (
            "table_wb_single_quote",
            wb.get("Single_Quote", []),
            "Word_Break = Single_Quote",
        ),
        (
            "table_wb_double_quote",
            wb.get("Double_Quote", []),
            "Word_Break = Double_Quote",
        ),
        ("table_wb_midnumlet", wb.get("MidNumLet", []), "Word_Break = MidNumLet"),
        ("table_wb_midletter", wb.get("MidLetter", []), "Word_Break = MidLetter"),
        ("table_wb_midnum", wb.get("MidNum", []), "Word_Break = MidNum"),
        ("table_wb_numeric", wb.get("Numeric", []), "Word_Break = Numeric"),
        (
            "table_wb_extendnumlet",
            wb.get("ExtendNumLet", []),
            "Word_Break = ExtendNumLet",
        ),
        ("table_wb_wsegspace", wb.get("WSegSpace", []), "Word_Break = WSegSpace"),
    ]

    for name, ranges, doc in table_specs:
        out_lines.append(emit_interval_array(name, ranges, doc))

    out_path = os.path.join(moji, "property_tables.mbt")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(out_lines))
    print(f"wrote {out_path}", file=sys.stderr)
    for name, ranges, _ in table_specs:
        print(f"  {name}: {len(ranges)} ranges", file=sys.stderr)


if __name__ == "__main__":
    main()
